from datetime import datetime
current=datetime.now()
print(current)
form=current.strftime("%a")
print(form)
form1=current.strftime(("%Y-%m-%d %H:%M:%S"))
print(form1)
form2=current.strftime(("%m/%d/%Y"))
print(form2)
form3=current.strftime(("%d,%m %d,%Y"))
print(form3)
form4=current.strftime(("%d-%m-%Y %H:%M:%S %p"))
print(form4)
form5=current.strftime("%a-%m-d %H")